<?php

//TITLE
$title = 'Reviews';
//NAVIGATION
$subdir = 'project';
$highlight = 'reviews.php';



//Don't touch stuff after this line unless you know what you're doing:
//--------------------------------------------------------------------------
$DEBUG = false;

//header.php contains HTML for the top of the page [e.g. <head> and metadata]
//as well as PHP for generating the main navigation [dropdown menu]
include ('../header.php');
?>			
<div class="maintext">

<h2 style="margin-top: -10px">Reviews - Volume 1: </h2>
<h2 style="margin-top: -10px">The Selected Papers of Margaret Sanger, Volume 1, <a href="../publications/volume_i.php">The Woman Rebel, 1900-1928</a>, (2003)</h2>
<p>
<p>If you know of any other reviews, please bring them to the Project's attention: <a href="mailto:sanger.papers@nyu.edu"></a><a href="mailto:sanger.papers@gmail.com">sanger.papers@gmail.com</a>
<p>
<h3>Volume 1, Review #1</h3>  					
<p><img src="file:///C|/Users/esthe/Dropbox/MSPP-NYU/images/docedit.jpg" width="119" height="174" align="right" style="margin-left: 15px;" /></p>
  <p>Anyone who's not yet familiar with this evocative woman and her activism can get better acquainted by perusing The Selected Papers of Margaret Sanger, Volume I: The Woman Rebel, 1900-1928. Likewise, anyone who thinks that they already know MS will discover more about her complicated life and advocacy in this award-winning work. And the journey will be delightful...For over half a century, Margaret Sanger tried to pull sexuality and birth control 'out of the gutter of obscenity and into the light of human understanding.' The history of her work, presented in this well-crafted volume and presumably in the others in the series . . . should enlighten modern woman. We need to hear the tale of Sanger's hard fought battle to fully comprehend the dangerous health care precipice on which women stand today. Hopefully Sanger's work will inspire us to confront and change policy, so that her efforts will not have been in vain." --Jimmy Meyer, ""From the Gutter of Obscenity," <i>Documentary Editing</i> 28:4 (Winter 2006), 184-94. </p>

      
<p><h3>Volume I, Review 2</h3> <img src="armlogo.gif" width="150" height="150" align="right" style="margin: 15px 0px 15px 15px;"></p>
 <p>The book allows insights into Sanger's motivations and actions, and traces the course of her relationships with family members, and with colleagues who were friends, such as Emma Goldman, or lovers, such as Havelock Ellis. . . .Faced with an archive of over 120,000 documents--letters, speeches, journals, and legal and organizational records--Esther Katz and her editorial team have chosen selections that document the critical events and central issues of Sanger's life. . . . Ultimately the work of Katz and her team is critical for a fuller understanding of first-wave feminism, family planning and one of the century's most interesting women, and I look forward to the next three volumes." -- Roxanne Harde,<em>Journal of the Association for Research on Mothering,</em> 6:1 (Spring/Summer 2004), pp. 205-206.</p>
      
 <p><h3>Volume I, Review 3</h3> <img src="file:///C|/Users/esthe/Dropbox/MSPP-NYU/images/iasrbar.gif" width="400" height="60" align="right"style="margin: 15px 0px 15px 15px;"></p>
<p>"This volume. . . marks the first publication of what is a major project which should be in libraries everywhere. It is scholarship at its highest level and when complete will be a standard work of reference for anyone interested in the development of birth control or the history of sex education not only in the United States but also in the rest of the world. It will also record the life of one of the most influential women of the twentieth century." -- Vern L. Bullough, <em>Archives of Sexual Behavior,</em> Vol. 33, No. 6, December 2004, pp. 611-612.</p>
      
<p><h3>Volume 1, Review 4</h3><img src="file:///C|/Users/esthe/Dropbox/MSPP-NYU/images/bhmcoversmall.gif" width="117" height="177" align="right"style="margin: 15px 0px 15px 15px;" >
</p>
<p>The publication of the first volume of Sanger’s selected papers is most welcome, in part because it provides a kind of reality check on the vast and proliferating nonsense about her that has been generated by zealots in our contemporary culture wars . . . .The meticulously edited first volume of her Selected Papers provides ready access to a complicated and compelling career. If you want to know the real woman who led the successful fight to remove the stigma of obscenity from contraception, this is an excellent place to begin." – James W. Reed, <em>Bulletin of the History of Medicine,</em> Spring 2004, 238-39. </p>

<p><h3>Volume I, Review 5</h3> <img src="file:///C|/Users/esthe/Dropbox/MSPP-NYU/images/socialservicereview.gif" width="158" height="239" align="right" style="margin: 15px 0px 15px 15px;"></p>
    
<p><em>Volume I, The Woman Rebel, 1900-1928,</em> draws primarily on Sanger's correspondence, supplemented by excerpts from her speeches, published articles, and journal entries, to trace the first 3 decades of her career. These documents are organized chronologically into chapters that reflect various phases of her life. Each section begins with an introduction that provides historical context and biographical detail. Every document is scrupulously annotated to identify unfamiliar people, places, events and terminology. In addition, researchers can use these endnotes to identify relevant archival materials that are not included in the volume. Given the extraordinary editorial work of Katz and her assistants, it is not too much to claim, as the publisher does, that the Woman Rebel can be read as a biography." --Kimberly Reilly, <em>Social Service Review,</em> Sep 2003, 487-88.</p>
        
<p><h3>Volume I, Review 6</h3> <img src="file:///C|/Users/esthe/Dropbox/MSPP-NYU/images/choice.gif" width="227" height="76" align="right" style="margin: 15px 0px 15px 15px;"></p> 
      
<p>In January 2004, Volume I was selected as one of Choice's "Outstanding Academic Titles"</p>
<p>The first in a four-book series, this compilation of letters Sanger wrote and received, speeches she gave, and other materials is more than a history of Sanger's efforts to promote birth control. The 250 documents detail Sanger's relationships in and outside marriage, her affiliations with many early 20th-century notables--Max Eastman, Emma Goldman, Havelock Ellis, H. G. Wells, and Carrie Chapman Catt, among others--and issues ranging from labor strikes to eugenics. The documents are remarkable for their content and sheer volume....Although two autobiographies and several biographies of her life exist, this collection is a welcome addition to Sanger scholarship. It allows readers to explore all aspects of her complex life and ideas. Readers might find her admirable and inspiring, then turn the page and find her maddening, arrogant, or irresponsible. Introductions to each section add context; readers can provide their own interpretation. The collection offers a wonderful window into Sanger and the early 20th-century US. Summing up: Highly Recommended. All levels and libraries." -- C. A. Kanes, <em>Choice: Current Reviews for Academic Libraries,</em> Sept. 2003.</p>
        
<p><h3>Volume I, Review 7</h3> 
<p>Volume 1: The Woman Rebel, 1900-1928</span> documents the formative years of one of America's most controversial and influential feminists. It details Margaret Higgins Sanger's difficult journey from working-class radical in pre-World War I bohemian Greenwich Village to upper-class celebrity who achieved mainstream respectability as she forged alliances with the medical profession in an ongoing crusade to ensure the right of every woman to determine whether and when to have children....The editorial team, headed by Esther Katz, the editor of the Margaret Sanger Papers Microfilm Edition, has assembled letters, diary excerpts, and essays, most of which have never been published, that offer significant insights into Sanger's struggles and accomplishments. Informative chapter introductions, along with meticulous annotations, allow readers to gain new insights into Sanger's crusade for birth control..." Judy Barrett-Litoff, <em>JAMA,</em> July 16, 2003, 408-9.</p>
        
<p><h3>Volume I, Review 8</h3> 
<img src="file:///C|/Users/esthe/Dropbox/MSPP-NYU/images/weekstan.jpeg" width="254" height="80" align="right" style="margin: 15px 0px 15px 15px;">
</p>
Somewhere, amidst the sucker punches and cries of foul, the truth must reside. And "somewhere," it turns out, is the enormous and altogether dazzling selection of public and private records just put out by the manuscript curators at New York University's "Margaret Sanger Papers Project." They too, like the earlier biographers, unambiguously admire the woman. But they have done their editing with scrupulous care, they have annotated the documents they reproduce with monk-like dispassion, and on the face of it they have held nothing back. "The Woman Rebel, 1900-1928" is the first in a projected four-volume series. For relevance to still unsettled political arguments, though, this volume, covering all the crucial years of Sanger's career, is clearly the one that matters." -- David Tell, "Planned Un-Parenthood: Roe v. Wade at thirty." <em>The Weekly Standard,</em> January 27, 2003, Volume 008, Issue 19.
<p><h3>Volume I, Review 9</h3>
</p>
"Mesmerizing letters from the days when birth control was legally obscene and jail sentences were regularly given out for talking about it in public. Nearly a century ago, Margaret Sanger was defending woman's 'ownership of her own body' and linking access to contraception to civil liberties and personal freedom. Rights we take for granted have a long and sometimes surprising history that comes clear on these pages. Required reading for our own time, whichever side of Roe v. Wade you are on." -- Linda K. Kerber, author of <em> No Constitutional Right to Be Ladies: Women and the Obligations of Citizenship</em.></p>
        
<p><h3>Volume I, Review 10</h3>
</p>
"These wonderful letters, diary excerpts, and essays dramatize women's long struggle for respect, self-awareness, independence, influence, and control over our bodies and our lives. To contemplate Margaret Sanger's harsh reality and the enduring vision of this courageous pioneer-- while the war against women escalates on every front-- is a heartening and galvanizing act of rebellion. Esther Katz and her splendid team have given us all a very great gift." -- Blanche Wiesen Cook, University Distinguished Professor, John Jay College and the Graduate Center, CUNY, and the author of <em>Eleanor Roosevelt,</em> volumes 1 and 2.
<p><h3>Volume I, Review 11</h3>
</p>
"This engrossing volume, meticulously edited and selected, captures Margaret Sanger in all her complexity during a formative period in her long career. Open to practically any page, and something will grab your historical attention." -- Susan Ware, editor of<em>Notable American Women,</em> volume 5.</p>

 
</div>

</div>

<?php
//Don't touch this unless you know what you're doing:
//--------------------------------------------------------------------------

//footer.php contains HTML for the bottom of the page [e.g. copyright notice]
//as well as PHP for generating the sidebar navigation
include ('../footer.php');
?>